### PR TITLE
Allow viewing elements not assigned to any group

### PR DESCRIPTION
**Pull request by SferaDev**
### 🔨 Implementation

- [x] Add an option in the ``Select``  to filter by elements not assigned to any group
- [x] Clear table if the user selects the default (empty) option
- [x] Do not crash if group has no elements
- [x] Add a column in the table to re-assign the element to another group
- [x] Render table even if there are no rows

### 🎨 Screenshots

image

image

### CODE REVIEW

**Review by adrianq — COMMENTED** [review]
@ifoche @SferaDev In terms of logic the feature works perfectly fine. Some comments/concerns:
- When you first click on DE Groups the actual DE Groups are automatically unselected. This is not very user-friendly in my opinion. Not sure how easy it would be to make the click action to work as append so to say.
- I would change 'Update Groups' for 'Apply' and maybe add a new button 'Cancel' that restore the original values. It would be great if this restore can be done without refreshing the webpage. For me, at least, it takes some time when refreshing the page for 'Not assigned to any group' Data Elements.
- The interface to select groups is a bit to narrow and ugly but this is the space we have and life is far too complex to be perfect but can we maybe do the filter one row larger?

Anyway, guys, you are the ones that have in mind the functional requirement so I am happy to go with whatever you decide.

**Comment by adrianq** [comment]
Btw, I have bumped the version in this branch to speed up the release process when ready!

**Comment by SferaDev** [comment]
> @ifoche @SferaDev In terms of logic the feature works perfectly fine. Some comments/concerns:
> 
> * When you first click on DE Groups the actual DE Groups are automatically unselected. This is not very user-friendly in my opinion. Not sure how easy it would be to make the click action to work as append so to say.

We're using the default HTML select multiple, so customization will be hard. The component is actually defined for each browser (look and feel may vary between Chrome, Firefox, Opera, ...)

> * I would change 'Update Groups' for 'Apply' and maybe add a new button 'Cancel' that restore the original values. It would be great if this restore can be done without refreshing the webpage. For me, at least, it takes some time when refreshing the page for 'Not assigned to any group' Data Elements.

I will take a look, it's true that it takes a lot of time for DE because there're a lot. These waits are normal through the app, but if I can apply the changes (rebuild the table) without reloading the request I will implement it.

> * The interface to select groups is a bit to narrow and ugly but this is the space we have and life is far too complex to be perfect but can we maybe do the filter one row larger?
> 

Yeah I though that maybe some of the columns are not needed in the main GUI but opened in the details pane, but I'm not sure about that.

**Comment by adrianq** [comment]
Well, columns are customizable through the table schema so no worries about that. Anyway, wait for Nacho regarding the second point. I am not sure how much time there is left for this task and how important this is...

**Comment by ifoche** [comment]
As per our conversation with @adrianq, I think that given that the deadline's tomorrow, maybe we can just go ahead and merge it creating a new issue with the comments from Adrian, which I find very appropriate.

**Comment by adrianq** [comment]
Issue created https://github.com/EyeSeeTea/datadictionary/issues/90 Merging PR and releasing

**Pull request merged**
