### PR TITLE
better look and feel for selection actions panel and table settings link

### PR DESCRIPTION
**Pull request by adrianq**

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland Can you review this PR very quickly and merge it if everything looks good? It is just some improvements on the look & feel of the table setting panel. I have removed [the spinner](https://github.com/EyeSeeTea/datadictionary/pull/80/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL492) as it introduces a strange unneeded gap between the buttons and the help icon. Were we actually using it for anything? If so, let me know and I will readd it. Thanks!

**Comment by adrianq** [comment]
I have just realised we were actually using it. So I have readded and played a bit with the css so we don't have that gap when it is not active. I think it looks fine. Give it a try and let me know!

**Review by tokland — APPROVED** [review]
Cool, looks much better. A minor detail: you used spaces in the HTML (it uses tabs), but let's leave it for another commit since there are spaces everywhere in the file.

**Comment by adrianq** [comment]
Yep, agreed. Indentation and format are a nightmare in the whole app. Something to look at in the future.

**Pull request merged**
